# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form1.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(743, 573)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setObjectName("listWidget")
        self.horizontalLayout.addWidget(self.listWidget)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.btnCreate = QtWidgets.QPushButton(self.centralwidget)
        self.btnCreate.setObjectName("btnCreate")
        self.verticalLayout.addWidget(self.btnCreate)
        self.btnUpd = QtWidgets.QPushButton(self.centralwidget)
        self.btnUpd.setObjectName("btnUpd")
        self.verticalLayout.addWidget(self.btnUpd)
        self.btnDel = QtWidgets.QPushButton(self.centralwidget)
        self.btnDel.setObjectName("btnDel")
        self.verticalLayout.addWidget(self.btnDel)
        self.horizontalLayout.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btnCreate.setText(_translate("MainWindow", "Создать"))
        self.btnUpd.setText(_translate("MainWindow", "Изменить"))
        self.btnDel.setText(_translate("MainWindow", "Удалить"))
